# vim: noai:ts=4:sw=4:expandtab
---
# file dev
- hosts: localhost
  pre_tasks:
    - debug: msg="use apt proxy {{ use_apt_proxy }}"
    - name: use mirrors
      lineinfile: dest=/etc/apt/sources.list insertbefore=BOF line={{item}}
      with_items:
        - "'deb mirror://mirrors.ubuntu.com/mirrors.txt {{ubuntu_release}} main restricted universe multiverse'"
        - "'deb mirror://mirrors.ubuntu.com/mirrors.txt {{ubuntu_release}}-updates main restricted universe multiverse'"
        - "'deb mirror://mirrors.ubuntu.com/mirrors.txt {{ubuntu_release}}-backports main restricted universe multiverse'"
        - "'deb mirror://mirrors.ubuntu.com/mirrors.txt {{ubuntu_release}}-security main restricted universe multiverse'"
      register: mirrors
      tags: configuration
      when: use_mirror
    - apt: update_cache=true
      when: mirrors.changed
      tags: configuration
    - block:
      - name: Pre-condition to create user
        apt: name=whois
      - name: create user
        file: path="{{home_base}}" state=directory mode=0755
      - group: name=docker
      - group: name=admin
      - user: name="{{user}}" shell=/bin/bash password="{{password}}" groups=admin,docker
      when: "user is defined"
    - name: configure apt-proxy
      template: src=templates/01proxy.j2 dest={{apt_proxy_conf}}
      when: use_apt_proxy == true
    - name: import keys
      apt_key: file="files/{{item}}"
      with_items:
        - "google-linux-signing-key.pub"
        - "webupd8team-java.pub"
        - "xubuntu.pub"
        - "docker-key.pub"
        - "ravefinity.pub"
  roles:
    - {role: angstwad.docker_ubuntu, docker_group_members: ["{{user}}"]}
    - {role: gnome-desktop, when: desktop == 'gnome'}
    - {role: xubuntu, when: desktop == 'xubuntu'}
    - {role: unity, when: desktop == 'unity'}
    - {role: vim, when: '"vim" in roles_included' }
    - {role: jekyll, when: '"jekyll" in roles_included' }
    - {role: virtualbox-guest, when: '"virtualbox-guest" in roles_included' }
    - {role: google-chrome, when: '"google-chrome" in roles_included' }
    - {role: dev-tools, when: '"dev-tools" in roles_included' }
    - {role: maven, when: '"maven" in roles_included' }
    - {role: nvm, when: '"nvm" in roles_included' }
    - {role: gvm, when: '"gvm" in roles_included' }
    - {role: intellij, when: '"intellij" in roles_included' }
    - {role: rvm, when: '"rvm" in roles_included' }
    - {role: asciidoc, when: '"asciidoc" in roles_included', tags: ['asciidoctor'] }
  post_tasks:
    - name: remove apt-proxy
      file: dest="{{apt_proxy_conf}}" state=absent
      when: remove_apt_proxy == true
  vars:
    # user: "dev"
    # user_name: "Richard Attermeyer"
    # user_email: "richard.attermeyer@gmail.com"
    # ubuntu_release: trusty
    # password: pleasechange --> generate e.g. using mkpasswd --method=SHA-512
    # password: "$6$R/NgeKnN$Nlq.TC54GwBbH3oWhonjLDXeGMH56JpnpIvXLzHNHUfvl7/YK8.dxf6BaASaJJh1mWr20OuS9kMEexiLbZ9xQ/"
    # home_base: "/home"
    # home: "{{home_base}}/{{user}}"
    # desktop: "unity"
    roles_included:
      - vim
      - jekyll
      - virtualbox-guest
      - google-chrome
      - dev-tools
      - maven
      - nvm
      - gvm
      - intellij
      - rvm
      - asciidoc
    use_mirror: false
  vars_files:
    - external_vars.yml
